export const bgColorDefault = 'bg-purple-400';
export const bgColorDisable = 'bg-purple-300';

export const listHoursAvalable = [
	{
		hourBook: '09:00',
		time: '00:30',
		services: [''],
		available: true,
		status: 'disponible',
		name: '',
		start: '',
		duration: '00:00',
	},
	{
		hourBook: '09:30',
		time: '00:30',
		services: [''],
		available: true,
		status: 'disponible',
		name: '',
		start: '',
		duration: '00:00',
	},
	{
		hourBook: '10:00',
		time: '00:30',
		services: [''],
		available: true,
		status: 'disponible',
		name: '',
		start: '',
		duration: '00:00',
	},
	{
		hourBook: '10:30',
		time: '00:30',
		services: [''],
		available: true,
		status: 'disponible',
		name: '',
		start: '',
		duration: '00:00',
	},
	{
		hourBook: '11:00',
		time: '00:30',
		services: [''],
		available: true,
		status: 'disponible',
		name: '',
		start: '',
		duration: '00:00',
	},
	{
		hourBook: '11:30',
		time: '00:30',
		services: [''],
		available: true,
		status: 'disponible',
		name: '',
		start: '',
		duration: '00:00',
	},
	{
		hourBook: '12:00',
		time: '00:30',
		services: [''],
		available: true,
		status: 'disponible',
		name: '',
		start: '',
		duration: '00:00',
	},
	{
		hourBook: '12:30',
		time: '00:30',
		services: [''],
		available: true,
		status: 'disponible',
		name: '',
		start: '',
		duration: '00:00',
	},
	{
		hourBook: '13:00',
		time: '00:30',
		services: [''],
		available: true,
		status: 'disponible',
		name: '',
		start: '',
		duration: '00:00',
	},
	{
		hourBook: '13:30',
		time: '00:30',
		services: [''],
		available: true,
		status: 'disponible',
		name: '',
		start: '',
		duration: '00:00',
	},
	{
		hourBook: '14:00',
		time: '00:30',
		services: [''],
		available: true,
		status: 'disponible',
		name: '',
		start: '',
		duration: '00:00',
	},
	{
		hourBook: '14:30',
		time: '00:30',
		services: [''],
		available: true,
		status: 'disponible',
		name: '',
		start: '',
		duration: '00:00',
	},
	{
		hourBook: '15:00',
		time: '00:30',
		services: [''],
		available: true,
		status: 'disponible',
		name: '',
		start: '',
		duration: '00:00',
	},
	{
		hourBook: '15:30',
		time: '00:30',
		services: [''],
		available: true,
		status: 'disponible',
		name: '',
		start: '',
		duration: '00:00',
	},
	{
		hourBook: '16:00',
		time: '00:30',
		services: [''],
		available: true,
		status: 'disponible',
		name: '',
		start: '',
		duration: '00:00',
	},
	{
		hourBook: '16:30',
		time: '00:30',
		services: [''],
		available: true,
		status: 'disponible',
		name: '',
		start: '',
		duration: '00:00',
	},
	{
		hourBook: '17:00',
		time: '00:30',
		services: [''],
		available: true,
		status: 'disponible',
		name: '',
		start: '',
		duration: '00:00',
	},
	{
		hourBook: '17:30',
		time: '00:30',
		services: [''],
		available: true,
		status: 'disponible',
		name: '',
		start: '',
		duration: '00:00',
	},
	{
		hourBook: '18:00',
		time: '00:30',
		services: [''],
		available: true,
		status: 'disponible',
		name: '',
		start: '',
		duration: '00:00',
	},
	{
		hourBook: '18:30',
		time: '00:30',
		services: [''],
		available: true,
		status: 'disponible',
		name: '',
		start: '',
		duration: '00:00',
	},
	{
		hourBook: '19:00',
		time: '00:30',
		services: [''],
		available: true,
		status: 'disponible',
		name: '',
		start: '',
		duration: '00:00',
	},
];

export const listBookDays = [
	{
		day: '03/06/2024',
		book: [
			{
				hourBook: '09:30',
				duration: '00:30',
				services: ['Manicure classica'],
				type: 'manicure',
				name: 'Anna',
			},
			{
				hourBook: '10:00',
				duration: '01:00',
				services: ['Smalto gel'],
				type: 'manicure',
				name: 'Alessandra',
			},
			{
				hourBook: '17:30',
				duration: '00:30',
				services: ['Pedicure classica'],
				type: 'pedicure',
				name: 'Federica',
			},
			{
				hourBook: '18:00',
				duration: '00:30',
				services: ['Pedicure classica'],
				type: 'pedicure',
				name: 'Rosa',
			},
		],
	},
	{
		day: '04/06/2024',
		book: [
			{
				hourBook: '13:30',
				duration: '00:30',
				services: ['Manicure classica'],
				type: 'manicure',
				name: 'Anna',
			},
			{
				hourBook: '12:00',
				duration: '01:00',
				services: ['Smalto gel'],
				type: 'manicure',
				name: 'Alessandra',
			},
			{
				hourBook: '16:30',
				duration: '00:30',
				services: ['Pedicure classica'],
				type: 'pedicure',
				name: 'Federica',
			},
			{
				hourBook: '18:30',
				duration: '00:30',
				services: ['Pedicure classica'],
				type: 'pedicure',
				name: 'Rosa',
			},
		],
	},
	{
		day: '05/06/2024',
		book: [
			{
				hourBook: '13:30',
				duration: '00:30',
				services: ['Manicure classica'],
				type: 'manicure',
				name: 'Anna',
			},
			{
				hourBook: '12:00',
				duration: '01:00',
				services: ['Smalto gel'],
				type: 'manicure',
				name: 'Alessandra',
			},
			{
				hourBook: '18:30',
				duration: '00:30',
				services: ['Pedicure classica'],
				type: 'pedicure',
				name: 'Federica',
			},
			{
				hourBook: '15:30',
				duration: '00:30',
				services: ['Pedicure classica'],
				type: 'pedicure',
				name: 'Rosa',
			},
		],
	},
];

export const servicesManicure = [
	{
		services: 'Copertura unghia naturale in gel',
		type: 'manicure',
		time: '01:30',
		bookingTime: '00:00',
	},
	{
		services: 'Copertura unghia naturale con semipermanente',
		type: 'manicure',
		time: '01:00',
		bookingTime: '00:00',
	},
	{
		services: 'Ricostruzione unghie in gel con cartina',
		type: 'manicure',
		time: '02:00',
		bookingTime: '00:00',
	},
	{
		services: 'Dry manicure',
		type: 'manicure',
		time: '00:30',
		bookingTime: '00:00',
	},
];

export const servicesPedicure = [
	{
		services: 'Semipermamente piedi',
		type: 'pedicure',
		time: '01:00',
		bookingTime: '00:00',
	},
	{
		services: 'Pedicure curativo',
		type: 'pedicure',
		time: '01:30',
		bookingTime: '00:00',
	},
];
