export const bgColorDefault = 'bg-red-400';
export const bgColorDisable = 'bg-purple-300';

export const books = {
	id: '',
	hourBook: '09:00',
	time: '00:30',
	services: [''],
	available: true,
	dayBook: 0,
	status: 'disponible',
	reservarName: '',
	usersId: '',
	start: '',
	duration: '00:00',
};

export const listHoursAvalable = [
	{
		id: '',
		hourBook: '09:00',
		time: '00:30',
		services: [''],
		available: true,
		dayBook: 0,
		status: 'disponible',
		reservarName: '',
		usersId: '',
		start: '',
		duration: '00:00',
	},
	{
		id: '',
		hourBook: '09:30',
		time: '00:30',
		services: [''],
		available: true,
		dayBook: 0,
		status: 'disponible',
		reservarName: '',
		usersId: '',
		start: '',
		duration: '00:00',
	},
	{
		id: '',
		hourBook: '10:00',
		time: '00:30',
		services: [''],
		available: true,
		dayBook: 0,
		status: 'disponible',
		reservarName: '',
		usersId: '',
		start: '',
		duration: '00:00',
	},
	{
		id: '',
		hourBook: '10:30',
		time: '00:30',
		services: [''],
		available: true,
		dayBook: 0,
		status: 'disponible',
		reservarName: '',
		usersId: '',
		start: '',
		duration: '00:00',
	},
	{
		id: '',
		hourBook: '11:00',
		time: '00:30',
		services: [''],
		available: true,
		dayBook: 0,
		status: 'disponible',
		reservarName: '',
		usersId: '',
		start: '',
		duration: '00:00',
	},
	{
		id: '',
		hourBook: '11:30',
		time: '00:30',
		services: [''],
		available: true,
		dayBook: 0,
		status: 'disponible',
		reservarName: '',
		usersId: '',
		start: '',
		duration: '00:00',
	},
	{
		id: '',
		hourBook: '12:00',
		time: '00:30',
		services: [''],
		available: true,
		dayBook: 0,
		status: 'disponible',
		reservarName: '',
		usersId: '',
		start: '',
		duration: '00:00',
	},
	{
		id: '',
		hourBook: '12:30',
		time: '00:30',
		services: [''],
		available: true,
		dayBook: 0,
		status: 'disponible',
		reservarName: '',
		usersId: '',
		start: '',
		duration: '00:00',
	},
	{
		id: '',
		hourBook: '13:00',
		time: '00:30',
		services: [''],
		available: true,
		dayBook: 0,
		status: 'disponible',
		reservarName: '',
		usersId: '',
		start: '',
		duration: '00:00',
	},
	{
		id: '',
		hourBook: '13:30',
		time: '00:30',
		services: [''],
		available: true,
		dayBook: 0,
		status: 'disponible',
		reservarName: '',
		usersId: '',
		start: '',
		duration: '00:00',
	},
	{
		id: '',
		hourBook: '14:00',
		time: '00:30',
		services: [''],
		available: true,
		dayBook: 0,
		status: 'disponible',
		reservarName: '',
		usersId: '',
		start: '',
		duration: '00:00',
	},
	{
		id: '',
		hourBook: '14:30',
		time: '00:30',
		services: [''],
		available: true,
		dayBook: 0,
		status: 'disponible',
		reservarName: '',
		usersId: '',
		start: '',
		duration: '00:00',
	},
	{
		id: '',
		hourBook: '15:00',
		time: '00:30',
		services: [''],
		available: true,
		dayBook: 0,
		status: 'disponible',
		reservarName: '',
		usersId: '',
		start: '',
		duration: '00:00',
	},
	{
		id: '',
		hourBook: '15:30',
		time: '00:30',
		services: [''],
		available: true,
		dayBook: 0,
		status: 'disponible',
		reservarName: '',
		usersId: '',
		start: '',
		duration: '00:00',
	},
	{
		id: '',
		hourBook: '16:00',
		time: '00:30',
		services: [''],
		available: true,
		dayBook: 0,
		status: 'disponible',
		reservarName: '',
		usersId: '',
		start: '',
		duration: '00:00',
	},
	{
		id: '',
		hourBook: '16:30',
		time: '00:30',
		services: [''],
		available: true,
		dayBook: 0,
		status: 'disponible',
		reservarName: '',
		usersId: '',
		start: '',
		duration: '00:00',
	},
	{
		id: '',
		hourBook: '17:00',
		time: '00:30',
		services: [''],
		available: true,
		dayBook: 0,
		status: 'disponible',
		reservarName: '',
		usersId: '',
		start: '',
		duration: '00:00',
	},
	{
		id: '',
		hourBook: '17:30',
		time: '00:30',
		services: [''],
		available: true,
		dayBook: 0,
		status: 'disponible',
		reservarName: '',
		usersId: '',
		start: '',
		duration: '00:00',
	},
	{
		id: '',
		hourBook: '18:00',
		time: '00:30',
		services: [''],
		available: true,
		dayBook: 0,
		status: 'disponible',
		reservarName: '',
		usersId: '',
		start: '',
		duration: '00:00',
	},
	{
		id: '',
		hourBook: '18:30',
		time: '00:30',
		services: [''],
		available: true,
		dayBook: 0,
		status: 'disponible',
		reservarName: '',
		usersId: '',
		start: '',
		duration: '00:00',
	},
	{
		id: '',
		hourBook: '19:00',
		time: '00:30',
		services: [''],
		available: true,
		dayBook: 0,
		status: 'disponible',
		reservarName: '',
		usersId: '',
		start: '',
		duration: '00:00',
	},
];

export const servicesManicure = [
	{
		services: 'Copertura unghia naturale in gel',
		type: 'manicure',
		duration: '01:30',
	},
	{
		services: 'Copertura unghia naturale con semipermanente',
		type: 'manicure',
		duration: '01:00',
	},
	{
		services: 'Ricostruzione unghie in gel con cartina',
		type: 'manicure',
		duration: '02:00',
	},
	{
		services: 'Dry manicure',
		type: 'manicure',
		duration: '00:30',
	},
];

export const servicesPedicure = [
	{
		services: 'Semipermamente piedi',
		type: 'pedicure',
		duration: '01:00',
	},
	{
		services: 'Pedicure curativo',
		type: 'pedicure',
		duration: '01:30',
	},
];

export const styleToast = {
	width: '300px',
	margin: '10px auto',
};
